# Generated by Django 5.1.1 on 2024-10-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaModelos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='fecha_prestamo',
        ),
    ]
