# Generated by Django 5.1.1 on 2024-10-18 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaModelos', '0002_remove_prestamos_fecha_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='fecha_prestamo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
